services:
  - type: web
    name: segmentation-app
    env: python
    plan: free
    repo: https://github.com/baanva02/segmentation-app-Potsdam-
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GDRIVE_FILE_ID
        value: 1gKCR8pXAUwfk1kflaz3YTYwHLwrVvQ5_
